// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace E_CommerceApp.Models
{
    public partial class ECommDBContext : DbContext
    {
        public ECommDBContext()
        {
        }

        public ECommDBContext(DbContextOptions<ECommDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductsOrder> ProductsOrders { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Order>(entity =>
            {
                entity.Property(e => e.orderID).ValueGeneratedNever();

                entity.Property(e => e.date)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.user)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.userID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Orders_Users");
            });

            modelBuilder.Entity<Product>(entity =>
            {
                entity.Property(e => e.productID).ValueGeneratedNever();

                entity.Property(e => e.category)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.description)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.price).HasColumnType("decimal(18, 0)");

                entity.Property(e => e.productName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<ProductsOrder>(entity =>
            {
                entity.HasKey(e => e.poID);

                entity.Property(e => e.poID).ValueGeneratedNever();

                entity.HasOne(d => d.order)
                    .WithMany(p => p.ProductsOrders)
                    .HasForeignKey(d => d.orderID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ProductsOrders_Orders");

                entity.HasOne(d => d.product)
                    .WithMany(p => p.ProductsOrders)
                    .HasForeignKey(d => d.productID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ProductsOrders_Products");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.userID).ValueGeneratedNever();

                entity.Property(e => e.email)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.password)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.userName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}