// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceApp.Models
{
    public partial class Order
    {
        public Order()
        {
            ProductsOrders = new HashSet<ProductsOrder>();
        }

        public int orderID { get; set; }
        public int userID { get; set; }
        public string date { get; set; }
        public double totalPrice { get; set; }

        public virtual User user { get; set; }
        public virtual ICollection<ProductsOrder> ProductsOrders { get; set; }
    }
}