// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceApp.Models
{
    public partial class Product
    {
        public Product()
        {
            ProductsOrders = new HashSet<ProductsOrder>();
        }

        public int productID { get; set; }
        public string productName { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public int quantity { get; set; }
        public string category { get; set; }

        public virtual ICollection<ProductsOrder> ProductsOrders { get; set; }
    }
}