// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_CommerceApp.Models
{
    public partial class ProductsOrder
    {
        public int poID { get; set; }
        public int orderID { get; set; }
        public int productID { get; set; }

        public virtual Order order { get; set; }
        public virtual Product product { get; set; }
    }
}